name: Run Tests on pull request
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit exists in origin/main
        run: echo "Going to use ${{ github.run_number }} for the package Id."

      - name: Set Version
        env:
          NUM: ${{ github.run_number }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo ::set-env name=VERSION::1.1.$(($NUM))-pr  # change int to current version when bumping

      - name: Test version (write)
        run: echo ${VERSION}

      - name: Build
        run: dotnet build ./source/Sailfish/Sailfish.csproj --configuration Release /p:Version=${VERSION}-pull-request

      - name: Build Adapter
        run: dotnet build ./source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj --configuration Release /p:Version=${VERSION}

      - name: Build Analyzer
        run: dotnet build ./source/Sailfish.Analyzers/Sailfish.Analyzers.csproj --configuration Release /p:Version=${VERSION}

      - name: Test
        run: dotnet test ./source/Tests.Sailfish/Tests.Sailfish.csproj --verbosity normal

      - name: Test Adapter
        run: dotnet test ./source/Tests.Sailfish.TestAdapter/Tests.Sailfish.TestAdapter.csproj --verbosity normal

      - name: Test Analyzer
        run: dotnet test ./source/Tests.Sailfish.Analyzers/Tests.Sailfish.Analyzers.csproj --verbosity normal

      - name: Pack
        run: dotnet pack ./source/Sailfish/Sailfish.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

      - name: Pack Adapter
        run: dotnet pack ./source/Sailfish.TestAdapter/Sailfish.TestAdapter.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .

      - name: Pack Analyzers
        run: dotnet pack ./source/Sailfish.Analyzers/Sailfish.Analyzers.csproj --configuration Release /p:Version=${{ env.VERSION }} --no-build --output .
